# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gqstvkb_4BYhKs54HhWM9Q8KCEp_9tDD
"""

# extract_var.py

import rpy2.robjects as robjects
import sys

# Carregar o arquivo R
robjects.r['source']('temp_prev_vf2.R')

# Recuperar a variável
var_name = sys.argv[1]
var_value = robjects.r[var_name]

# Imprimir o valor
print(var_value[0])